version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: aqi_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./model:/app/model
    networks:
      - aqi_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: aqi_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    volumes:
      - ./frontend:/app
    networks:
      - aqi_network

networks:
  aqi_network:
    driver: bridge