version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: aqi-api
    ports:
      - "8000:8000"
    networks:
      - aqi-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: aqi-frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    networks:
      - aqi-net

networks:
  aqi-net:
    driver: bridge